version: "3.9"

services:
  postgres:
    image: docker.io/postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: