[package]
name = "todone-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
todone-core = {path = "../todone-core", features = ["back"]}

sqlx = { version = "0.6.2", features = [ "runtime-tokio-native-tls" , "postgres", "offline"] }
tokio = { version = "1.21.2", features = ["full"] }
axum = "0.6.0-rc.2"
clap = { version = "4.0.10", features = ["derive", "env"]}
dotenv = "0.15.0"
anyhow = "1.0.65"
thiserror = "1.0.37"
serde = { version = "1.0.145", features = ["derive"] }
serde_with = { version = "2.0.0" }
serde_json = "1.0.85"
argon2 = "0.4.1"
validator = { version = "0.16.0", features = ["derive"] }
rand = "0.8.5"
once_cell = "1.15.0"
regex = "1.6.0"
jsonwebtoken = "8.1.1"
